name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Verhindert parallele Deployments
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production --base-href "/one-year-anniversary/"

      - name: Fix routing – copy index.html to 404.html
        run: |
          cp dist/one-year-anniversary/browser/index.csr.html dist/one-year-anniversary/browser/index.html
          cp dist/one-year-anniversary/browser/index.csr.html dist/one-year-anniversary/browser/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist/one-year-anniversary/browser"

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4